### ISSUE TITLE
Update Install Procedure for Installing Prerequisites

### ISSUE THREAD

**Issue by clay584** [rfdrake/tel#3]
In order to get this installed I had to install CPAN and then install several modules.  The author may want to add those prerequisites to the install documentation.

Centos 6.5:

sudo yum install cpan
cpan App:cpanminus
sudo cpan Module::Install
cpan -f Hash::Merge::Simple
sudo cpan IO::Stty

**Comment by rfdrake** [comment]
The install process has changed a bunch in the last 6 years.  I think the easiest method now is to use cpanminus to directly install from CPAN,
